### ISSUE TITLE
Problem with the script 

### ISSUE THREAD

**Issue by TheTerminator2** [justinclarkhome/AlphaVantageStockDB#1]
Made a MYSQL database (not local) with two databases and run the script, but got the following error. 

python updater.py --daily --intraday

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
2018-09-16 10:48:46,470 - INFO - USING DATABASE: PRICES_DAILY
Traceback (most recent call last):
  File "updater.py", line 559, in <module>
    tickers=tickers)
  File "updater.py", line 237, in database_update
    data_source_id = fetchone(sql_cursor, query="SELECT GetDataSourceIDFromDataSourceName('{}')".format(data_source_name))
  File "updater.py", line 48, in fetchone
    sql_cursor.execute(query)
  File "/anaconda3/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/anaconda3/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/anaconda3/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/anaconda3/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1305, 'FUNCTION PRICES_DAILY.GetDataSourceIDFromDataSourceName does not exist')

**Comment by justinclarkhome** [comment]
Hi -

Did you run the SQL create scripts first (rather than manually creating the
databases)? They'll generate the databases and all the
tables/functions/procedures required.

Justin

**Comment by TheTerminator2** [comment]
Hi

I found the error, I wasn't having SUPER privilege in AWS when making the MYSQL database. But when using the advice from this link ( https://github.com/soundcloud/lhm/issues/76 ) and got the super privilege rights everythink works out fine. Thank you for the fast comment.

**Comment by justinclarkhome** [comment]
Nice - glad you got it sorted!

**Comment by justinclarkhome** [comment]
Glad you got that sorted!

On Sep 16, 2018 15:07, "TheTerminator2" <notifications@github.com> wrote:

Hi

I found the error, I wasn't having SUPER privilege in AWS when making the
MYSQL database. But when using the advice from this link ( soundcloud/lhm#76
<https://github.com/soundcloud/lhm/issues/76> ) and got the super privilege
rights everythink works out fine. Thank you for the fast comment.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/justinclarkhome/AlphaVantageStockDB/issues/1#issuecomment-421814729>,
or mute the thread
